# Generated by Django 5.1.1 on 2024-09-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('which_teacher_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='id_prof',
        ),
        migrations.AddField(
            model_name='professor',
            name='confirma_senha',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='professor',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='professor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='senha',
            field=models.CharField(max_length=255),
        ),
    ]
