# Generated by Django 5.1.1 on 2024-10-29 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('which_teacher_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrelas', models.IntegerField()),
                ('comentario', models.TextField(max_length=500)),
                ('id_aluno', models.IntegerField()),
                ('nome_aluno', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='horario',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='assunto',
        ),
        migrations.AddField(
            model_name='horario',
            name='dia_semana',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turma',
            name='professor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='which_teacher_app.professor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='professor',
            name='materia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='turma',
            name='alunos',
            field=models.ManyToManyField(to='which_teacher_app.aluno'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='materia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='turma',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.CharField(max_length=255)),
                ('meio_transmissao', models.CharField(max_length=50)),
                ('meio_pagamento', models.CharField(max_length=50)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='which_teacher_app.professor')),
            ],
        ),
    ]
