# Generated by Django 5.1.1 on 2024-10-23 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('which_teacher_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='assunto',
        ),
        migrations.AddField(
            model_name='turma',
            name='professor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='which_teacher_app.professor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='professor',
            name='materia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='turma',
            name='alunos',
            field=models.ManyToManyField(to='which_teacher_app.aluno'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='materia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='turma',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
