# Generated by Django 5.1.1 on 2024-10-24 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('which_teacher_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='media/perfil_professor/'),
        ),
    ]
