# Generated by Django 5.1.1 on 2024-11-07 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('which_teacher_app', '0002_avaliacao_remove_horario_dia_remove_turma_assunto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('comment', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='which_teacher_app.aluno')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='which_teacher_app.professor')),
            ],
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='professor',
        ),
        migrations.DeleteModel(
            name='Avaliacao',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='dia_semana',
        ),
        migrations.AddField(
            model_name='horario',
            name='dia',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Agendamento',
        ),
    ]
