# Generated by Django 5.1.1 on 2024-11-07 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('which_teacher_app', '0003_review_remove_agendamento_aluno_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrelas', models.IntegerField()),
                ('comentario', models.TextField(max_length=500)),
                ('id_aluno', models.IntegerField()),
                ('nome_aluno', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='horario',
            name='dia',
        ),
        migrations.AddField(
            model_name='horario',
            name='dia_semana',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='idade',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nivel_ensino',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='professor',
            name='nivel_ensino',
            field=models.CharField(choices=[('ensino_fundamental', 'Ensino Fundamental'), ('ensino_medio', 'Ensino Médio'), ('ensino_superior', 'Ensino Superior')], max_length=100),
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('meio_transmissao', models.CharField(max_length=50)),
                ('meio_pagamento', models.CharField(max_length=50)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='which_teacher_app.professor')),
            ],
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
