# Generated by Django 5.1.1 on 2024-11-08 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('which_teacher_app', '0004_avaliacao_remove_horario_dia_horario_dia_semana_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Horario',
        ),
    ]
