# Generated by Django 5.1 on 2024-09-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('which_teacher_app', '0005_professor_celular_professor_comunicacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='genero',
        ),
        migrations.AlterField(
            model_name='professor',
            name='comunicacao',
            field=models.CharField(blank=True, choices=[('meet', 'Meet'), ('zoom', 'Zoom'), ('discord', 'Discord')], max_length=255),
        ),
        migrations.AlterField(
            model_name='professor',
            name='materia',
            field=models.CharField(blank=True, choices=[('Matemática', 'Matemática'), ('português', 'Português'), ('Geografia', 'Geografia'), ('História', 'História'), ('inglês', 'Inglês'), ('computação', 'computação')], max_length=255),
        ),
        migrations.AlterField(
            model_name='professor',
            name='nivel_ensino',
            field=models.CharField(blank=True, choices=[('fundamental', 'Fundamental'), ('medio', 'Médio'), ('superior', 'Superior')], max_length=255),
        ),
        migrations.AlterField(
            model_name='professor',
            name='recebimento',
            field=models.CharField(blank=True, choices=[('pix', 'Pix'), ('cartao', 'Cartão'), ('boleto', 'Boleto')], max_length=255),
        ),
    ]
