# Generated by Django 5.1.1 on 2024-11-09 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('which_teacher_app', '0005_delete_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='which_teacher_app.aluno'),
        ),
    ]
