# Generated by Django 5.1 on 2024-09-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('which_teacher_app', '0006_remove_professor_genero_alter_professor_comunicacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='genero',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
