# Generated by Django 5.1.1 on 2024-11-09 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('which_teacher_app', '0006_alter_agendamento_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='professor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='which_teacher_app.professor'),
            preserve_default=False,
        ),
    ]
