# Generated by Django 5.1.1 on 2024-11-09 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('which_teacher_app', '0007_avaliacao_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='perfil_aluno/'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='objetivo_estudo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
