# Generated by Django 5.1.1 on 2024-11-09 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('which_teacher_app', '0008_aluno_imagem_aluno_objetivo_estudo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetivoEstudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('progresso', models.IntegerField(default=0)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='which_teacher_app.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='TarefaObjetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('concluida', models.BooleanField(default=False)),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='which_teacher_app.objetivoestudo')),
            ],
        ),
    ]
