# Generated by Django 5.1.1 on 2024-09-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('which_teacher_app', '0008_alter_professor_celular_alter_professor_comunicacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
